# Generated by Django 4.1.3 on 2022-11-15 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('number', models.TextField(max_length=15)),
            ],
            options={
                'unique_together': {('name', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salwar_length', models.TextField(blank=True, max_length=8, null=True)),
                ('salwar_shoulder', models.TextField(blank=True, max_length=8, null=True)),
                ('salwar_chest', models.TextField(blank=True, max_length=8, null=True)),
                ('salwar_waist', models.TextField(blank=True, max_length=8, null=True)),
                ('salwar_neck', models.TextField(blank=True, max_length=8, null=True)),
                ('salwar_sleeve', models.TextField(blank=True, max_length=8, null=True)),
                ('salwar_bottom', models.TextField(blank=True, max_length=8, null=True)),
                ('blouse_length', models.TextField(blank=True, max_length=8, null=True)),
                ('blouse_shoulder', models.TextField(blank=True, max_length=8, null=True)),
                ('blouse_chest', models.TextField(blank=True, max_length=8, null=True)),
                ('blouse_waist', models.TextField(blank=True, max_length=8, null=True)),
                ('blouse_neck', models.TextField(blank=True, max_length=8, null=True)),
                ('blouse_sleeve', models.TextField(blank=True, max_length=8, null=True)),
                ('blouse_bottom', models.TextField(blank=True, max_length=8, null=True)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('due_date', models.DateField()),
                ('image', models.TextField(blank=True, max_length=500, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
