# Generated by Django 4.1.3 on 2022-11-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_item_due_date_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.TextField(blank=True, max_length=75, null=True),
        ),
    ]
